# Generated by Django 5.1.1 on 2024-10-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='descricao',
            field=models.CharField(default='Descrição', max_length=150),
        ),
    ]
